version: '2'

volumes:
    pg_vol:

services:
    pg:
        image: postgres:9.6
        environment:
            - PGDATA=/var/lib/postgresql/data/pgdata
            - POSTGRES_DB=ww_dev
            - POSTGRES_USER=ww_user
            - POSTGRES_PASSWORD=ww_pw
        volumes:
            - pg_vol:/var/lib/postgresql/data
        ports:
            - 5432:5432

    ww:
        image: yiisoftware/yii2-php:7.1-apache
        environment:
            - POSTGRES_HOST=pg
        volumes:
            - .:/opt/ww
        ports:
            - 8080:8080
        depends_on:
            - pg
        working_dir: /opt/ww
#        entrypoint: bash -c "chmod -R 777 * && composer install -v && php /opt/ww/yii serve 0.0.0.0:8080"
        entrypoint: bash -c "chmod -R 777 * && composer install -v && apt-get update && apt-get install -y imagemagick ghostscript zip && php /opt/ww/yii serve 0.0.0.0:8080"